---
# tasks file for ansible-mysql

- name: Install MySQL packages
  ansible.builtin.include_tasks: install.yml
  tags:
    - install_mysql_server
    - install_mysql_client
    - install

- name: Configure MySQL server
  ansible.builtin.include_tasks: configure.yml
  tags:
    - configure_mysql_server
    - configure

- name: Create MySQL user(s)
  ansible.builtin.include_tasks: create_user.yml
  tags:
    - create_user
    - create

- name: Create MySQL database(s)
  ansible.builtin.include_tasks: create_db.yml
  tags:
    - create_db
    - create
