---
# Teardown tasks for mysql. This will remove mysql from the server.
# This is useful for when you want to remove services and configurations from the server.
- name: Stop and disable mysqld
  become: true
  service:
    name: mysqld
    state: stopped
    enabled: false

- name: Remove MySQL server
  become: true
  apt:
    name: "{{ item }}"
    state: absent
    purge: true
    autoremove: true
  with_items:
    - mysql-server
    - mysql-common
    - mysql-server-core-*
    - python-mysqldb
  register: mysql_uninstalled

- name: Remove MySQL client
  become: true
  apt:
    name: "{{ item }}"
    state: absent
    purge: true
    autoremove: true
  with_items:
    - mysql-client
    - mysql-client-core-*
  when: mysql_client_install is true

- name: Remove MySQL configuration
  become: true
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /etc/mysql/
  when: mysql_uninstalled is changed
